rules:
  - id: detect-file-system-access
    pattern-either:
      - pattern: os.system("...")
      - pattern: subprocess.run("...")
      - pattern: subprocess.Popen("...")
      - pattern: open("...")
      - pattern: |
          os.path.join("...", "...")
    message: "Detected file system access - verify this is not accessing sensitive local paths"
    languages: [python]
    severity: WARNING

  - id: detect-path-traversal
    patterns:
      - pattern-either:
          - pattern: "../../"
          - pattern: "../"
          - pattern: "~/"
          - pattern: "/etc/"
          - pattern: "/root/"
          - pattern: "/home/"
    message: "Potential path traversal or sensitive directory access detected"
    languages: [python, javascript]
    severity: ERROR
