rules:
  - id: detect-javascript-process-execution
    pattern-either:
      - pattern: exec("...")
      - pattern: spawn("...")
      - pattern: child_process.exec("...")
      - pattern: child_process.spawn("...")
    message: "Detected process execution - verify command injection is not possible"
    languages: [javascript]
    severity: WARNING

  - id: detect-python-process-execution
    pattern-either:
      - pattern: os.system("...")
      - pattern: os.popen("...")
      - pattern: subprocess.run("...", ...)
      - pattern: subprocess.Popen("...", ...)
      - pattern: subprocess.call("...", ...)
      - pattern: subprocess.check_call("...", ...)
      - pattern: subprocess.check_output("...", ...)
      - pattern: eval("...")
      - pattern: exec("...")
    message: "Detected process execution - verify command injection is not possible"
    languages: [python]
    severity: WARNING
